modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      tls_config:
        ca_file: /etc/ssl/certs/ca-certificates.crt
  dns_pihole:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: ip4
      query_name: home.arpa
      query_type: A
      valid_rcodes: [NOERROR]
      validate_answer_rrs:
        fail_if_none_matches_regexp: ['10\.10\.20\.10']
