$include: shared/base.yml

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          $include: shared/sidebar.yml

      - size: full
        widgets:
          - type: monitor
            title: Services
            cache: 30s
            sites:
              - title: Kaneo
                url: https://${KANEO_HOSTNAME}
                icon: https://${KANEO_HOSTNAME}/favicon.ico
              - title: Outline
                url: https://${OUTLINE_HOSTNAME}
                icon: si:outline
              - title: Beaver Habits
                url: https://beaverhabits.svc.home.arpa
                icon: si:todoist

          - type: monitor
            title: Media
            cache: 30s
            sites:
              - title: Jellyfin
                url: http://100.116.110.63:8096/web
                check-url: http://192.168.50.39:8096/web
                icon: si:jellyfin
              - title: Radarr
                url: http://100.116.110.63:7878/radarr/
                check-url: http://192.168.50.39:7878/radarr/
                icon: si:radarr
              - title: Sonarr
                url: http://100.116.110.63:8989/sonarr/
                check-url: http://192.168.50.39:8989/sonarr/
                icon: si:sonarr

          - type: monitor
            title: Management
            cache: 30s
            sites:
              - title: Authelia
                url: https://auth.home.arpa
                icon: si:authelia
              - title: Pi-hole
                url: https://pihole.ops.home.arpa/admin/
                icon: si:pihole
              - title: Traefik
                url: https://traefik.ops.home.arpa/dashboard/
                icon: si:traefikproxy
              - title: Consul
                url: https://consul.ops.home.arpa/ui/
                icon: si:consul
              - title: Prometheus
                url: https://prometheus.ops.home.arpa
                icon: si:prometheus
              - title: UGOS
                url: https://100.116.110.63:9443/
                icon: si:ubiquiti
                allow-insecure: true

          - $include: shared/nodes.yml

  - $include: shared/monitoring.yml
