- type: clock
  hour-format: 24h
  timezones:
    - timezone: Asia/Singapore
      label: Singapore
- type: calendar
  first-day-of-week: monday
- type: weather
  location: Singapore, Singapore
  units: metric
  hour-format: 24h
